version: '3'

services:
  backend-master:
    build:
      context: ./master/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  frontend-master:
    build:
      context: ./master/frontend
      dockerfile: Dockerfile
      args:
        - NODE_TYPE=MASTER
    ports:
      - "3000:3000"
    depends_on:
      - backend-master

  backend-slave-fake:
    build:
      context: ./slave/backend
      dockerfile: Dockerfile
    environment:
      - SLAVE_ID=fake
    ports:
      - '5100:5000'

  frontend-slave-fake:
    build:
      context: ./slave/frontend
      dockerfile: Dockerfile
      args:
        - NODE_TYPE=SLAVE
    ports:
      - '3100:3000'
    depends_on:
      - backend-slave-fake
